[project]
name = "debate_self"
version = "0.1.0"
description = "debate_self using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[anthropic,tools]==1.6.1",
]

[project.scripts]
debate_self = "debate_self.main:run"
run_crew = "debate_self.main:run"
train = "debate_self.main:train"
replay = "debate_self.main:replay"
test = "debate_self.main:test"
run_with_trigger = "debate_self.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
